default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV["DB_PASSWORD"] %>
  reconnect: false

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "school_manager_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "school_manager_test") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_PRODUCTION", "school_manager_production") %>

  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CACHE", "school_manager_cache") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_QUEUE", "school_manager_queue") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME_CABLE", "school_manager_cable") %>
    migrations_paths: db/cable_migrate
